name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
          
      - name: Build
#        run: ./gradlew -Pversion=${GITHUB_REF_NAME} clean build
        run: echo "Building with version ${GITHUB_REF_NAME}"
          
#      - name: Create Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: build/distributions/*
